### ISSUE TITLE
Hello Discord

### ISSUE THREAD

**Issue by benbenlaw** [bbl-team/Modpack-Support#1]
### Modpack

None

### Version

all the versions

### Describe the bug

very buggy send help

### Steps to reproduce

1 make bug 

### Expected behaviour

no bug

### Screenshots

nah

### Additional information

nah

**Comment by benbenlaw** [comment]
no ben you cant do this

**Comment by CharZinta** [comment]
Ben is the coolest mod pack maker ever. This isn't a bug this is awesomeness

**Comment by CharZinta** [comment]
The issue is closed and I will now learn at the feet of the master

**Comment by CharZinta** [comment]
okay testing perms is fun lets really close it :)

**Comment by 901238746** [comment]
bro
