### ISSUE TITLE
Missin item in quest book

### ISSUE THREAD

**Issue by gaminggirl** [bbl-team/Modpack-Support#10]
### Modpack

Aeropolis

### Version

5.0 and 5.1

### Describe the bug

The moreautomation mod is no longer in the pack but the quest book asks for an auto workbench from it.

### Steps to reproduce

1. Open Quest book
2. Go to CCII
3. Find the question marked quest

### Expected behaviour

Something that can be crafted should be there

### Screenshots

![bild](https://github.com/bbl-team/Modpack-Support/assets/19671059/0af44fb9-4a80-4a56-ada1-965906d79421)

**Comment by Bebobobo** [comment]
there is a fix currently submitted and waiting approval. you can go to edit mode and fix it. the mod is there but the script broke.

**Comment by moody69420** [comment]
Update ur pack it’s already fixed mod was removed from the pack but quest didn’t get adjusted yet till 5.2
