### ISSUE TITLE
Slimeball not accepted as an non-unfamiliar item

### ISSUE THREAD

**Issue by MrPopannes** [bbl-team/Modpack-Support#12]
### Modpack

Stoneopolis

### Version

2.0

### Describe the bug

When trying to plant the lime sapling i got an error message:
"You do not know how to use the lime coloured sapling"

I´ve checked the quest book and noticed, that i have the knowledge for the magma cream but not for the slime ball. So the knowledge line is stuck at this stage even though i´ve completed the quests in line and the completion is recognised:
![image](https://github.com/bbl-team/Modpack-Support/assets/7689940/db4d941c-93af-4fa0-a218-d65e239f53b3)

Is there a way to unlock items/stages by command to get around the issue?

Great modpack, thanks for the efforts!

### Steps to reproduce

Not tried to reproduce as there is no info on how to unlock game stages by command.

### Expected behaviour

unlock slimeball after crafting

### Screenshots

![image](https://github.com/bbl-team/Modpack-Support/assets/7689940/61f8f45a-3936-4bbd-9f99-d7c3328617d7)

![image](https://github.com/bbl-team/Modpack-Support/assets/7689940/db4d941c-93af-4fa0-a218-d65e239f53b3)

![image](https://github.com/bbl-team/Modpack-Support/assets/7689940/b73ee0cc-08c3-4a34-bb5d-3cfe042ebb42)

**Comment by MrPopannes** [comment]
I´ve found the issue:
I´ve not unlocked the "hostile mobs" by crafting a stone sword.
Maybe one can make this a dependency to progress?

**Comment by benbenlaw** [comment]
fixed
