### ISSUE TITLE
FTBChunks not being loaded on server

### ISSUE THREAD

**Issue by OneComputerGuy** [bbl-team/Modpack-Support#17]
### Modpack

Stoneopolis

### Version

2.1

### Describe the bug

The configuration for FTB chunks is set to offload chunks (claimed and force loaded) when all the team members are offline. This is an issue when going single player in a server world (to keep stuff running when not online)

The current configuration under `ftbchunks-world.snbt` has the following:

```
        # Control how force-loaded chunks work.
        # NEVER: only allow chunk force-loading if the owning team has at least one online player.
        # ALWAYS: always allow force-loading, even if no players are online.
        # DEFAULT: allow force-loading IF the team has at least one player with the 'ftbchunks.chunk_load_offline' FTB Ranks permission.
        # Default: "default"
        # Valid values: "default", "always", "never"
        force_load_mode: "default"
```

Which defaults to at least one team player being online with a specific permission, but the `ranks.snbt` file doesn't have that permission either:

```
{
        member: {
                name: "Member"
                power: 1
                condition: "always_active"
        }
        vip: {
                name: "VIP"
                power: 50
                ftbranks.name_format: "&bVIP {name}"
        }
        admin: {
                name: "Admin"
                power: 1000
                condition: "op"
                ftbranks.name_format: "&2{name}"
        }
}
```

### Steps to reproduce

1. Launch a server
2. Access the server
3. Create an FTB Team
4. Open the inventory and click the Force load chunks button to the top left
5. Shift+click a chunk to force load it
6. Go back to the world a put a simple automation (a smelter with some chests and fuel should work)
7. Log out and wait a couple of minutes
8. Log back in and check the automation.

Expected behavior: Automation continues after log out
Observed behavior: Automation stops and only continues when the player logs back in.

### Expected behaviour

Forced chunks keeps being loaded after the player logs out

**Comment by moody69420** [comment]
These are settings you change if you want not pack wide changes. These are default settings after all.
