### ISSUE TITLE
Joining Techopolis 2 server fails with large packet error

### ISSUE THREAD

**Issue by metalim** [bbl-team/Modpack-Support#20]
### Modpack

Techopolis 2

### Version

7.0

### Describe the bug

![image](https://github.com/bbl-team/Modpack-Support/assets/230431/6a8be0ca-c160-4c9e-93fb-bf49f6b165ab)

Joining top.playcdu.co fails with this ^ error.
The only solution we found is to install "Packet Fixer" on the client side

### Steps to reproduce

Try to join top.playcdu.co with Techopolis 2 client 7.0

### Expected behaviour

should join

**Comment by CharZinta** [comment]
Please provide the crash log and the hs_pid log.
Did you put an item into an item, such as an ME drive into a backpack into your inventory or similar event?

**Comment by metalim** [comment]
> Did you put an item into an item, such as an ME drive into a backpack into your inventory or similar event?

No, it was fresh start. Failed several times, restart and reinstall didn't fix it, so I installed packet fixer and moved along. Could have been something in spawn area, can't confirm or deny

**Comment by CharZinta** [comment]
Player correction.. ticket closed
