### ISSUE TITLE
Exp with Essence Ore

### ISSUE THREAD

**Issue by XH14MZAH3** [bbl-team/Modpack-Support#21]
### Modpack

Techopolis 2

### Version

6.1

### Describe the bug

Breaking Essence Ore with pickaxe gives xp and the block back, can be placed again and again to give exp (not sure if this is intentional)

### Steps to reproduce

1. Get Essence Ore
2. Get a pickaxe
3. Break the Essence Ore
4. Place again
5. Repeat from 3.

### Expected behaviour

Not to give exp, and the information says it should give the essence from breaking the ore

**Comment by CharZinta** [comment]
Please update to the latest version of the pack and report of this continues.

**Comment by CharZinta** [comment]
Please follow the questlines. This is not a bug but rather you need to use the right item. This is a quest based pack.
