### ISSUE TITLE
Server Files for Techopolis 2

### ISSUE THREAD

**Issue by JulianVennen** [bbl-team/Modpack-Support#22]
### Modpack

Techopolis 2

### Describe the feature, mod or suggestion

You stopped uploading server files on CurseForge in version 7.1.
Are you planning to upload server files for new versions?

**Comment by benbenlaw** [comment]
7.0 server files work with this version

**Comment by JulianVennen** [comment]
Does that also apply to 7.2?

**Comment by benbenlaw** [comment]
Yep
