### ISSUE TITLE
Tossing Mob Essence blocks into lightning water softlocks your world

### ISSUE THREAD

**Issue by zhs2** [bbl-team/Modpack-Support#23]
### Modpack

Omniopolis

### Version

2.3

### Describe the bug

Creating lightning water and tossing Mob Essence blocks into that water causes Minecraft to hang, and eventually crash. Once you load up Minecraft again the world in which you did this can no longer be loaded (it sticks permanently at the 100% regions screen and continually prints timeout errors every minute to the log) without reverting to a backup or having some way to remove the ticking entity from the world. Thank god for backups.

### Steps to reproduce

1. Craft lightning rod, place in water
2. Craft lightning summoner, click on lightning rod in water
3. Drop Mob Essence blocks in that water
4. Kaboom

### Expected behaviour

I expected my Mob Essence blocks to float there waiting to be upgraded to the next tier of essence, as the instructions imply.

### Screenshots

![image](https://github.com/user-attachments/assets/f7218d44-b5be-48f4-af0c-61ddd2eaa716)

### Additional information

[Link to crash log](https://tireiron.us/crash-2024-07-21_20.07.11-server.txt)

**Comment by CharZinta** [comment]
After testing this appears to be a problem with how the essence mod interacts with the vanilla lightning rod.   This information, and confirmation of your steps above will be passed to the developer.  There are currently no later versions of this mod
@benbenlaw 

thank you for the detailed report made it easier to test out.

**Comment by zhs2** [comment]
"After testing this appears to be a problem with how the essence mod interacts with the vanilla lightning rod."
I actually bucketed the lightning water and put it into a different place without the waterlogged lightning rod before tossing in a quarter of a stack of essence blocks and getting the hard crash. I'm not certain how much of a difference the lightning rod makes.

**Comment by CharZinta** [comment]
This seems to be mod interaction with Ben's mod and Vanilla MC. Ben has moved onto 1.21 so no updates are expected.
