### ISSUE TITLE
Techopolis 2 Serverfiles on Curseforge are outdated

### ISSUE THREAD

**Issue by marius137** [bbl-team/Modpack-Support#24]
### Modpack

Techopolis 2

### Version

Techopolis 2 version 7.2

### Describe the bug

Downloading the Serverfiles Linked on Curseforge gives outdated Server Files

### Steps to reproduce

- Download the Serverfiles form Curseforge
- Setup Server
- Install Latest Techopolis
- Try to connect
- Get error about mismatched mod versions

### Expected behaviour

Get the current server files for the latest modpack version

### Additional information

The Serverfiles are dated April 3, so probably something around Techopolis 2-B3.0

**Comment by benbenlaw** [comment]
(https://www.curseforge.com/minecraft/modpacks/techopolis-2/files/5071829)

**Comment by benbenlaw** [comment]
7.0 server files are compatible with 7.2

**Comment by marius137** [comment]
OK, I just read how-to-make-a-server on Discord, perhaps you should mention that somewhere on the modpack page aswell. I downloaded the pack pinned in the sidebar
