### ISSUE TITLE
Skyblock Recipes incompatible with Refined Storage

### ISSUE THREAD

**Issue by C-Doug-iS** [bbl-team/Modpack-Support#25]
### Modpack

Techopolis 2

### Version

7.2

### Describe the bug

Skyblock specific recipes do not work inside the Refined Storage Crafting Grid.

They work just fine in Simple Storage Network Tables.

Recipes from other stages work just fine as well in Refined Storage.

### Steps to reproduce

![image](https://github.com/user-attachments/assets/a2f0e71e-96e9-4591-a4b4-869fcd686d30)
![image](https://github.com/user-attachments/assets/9e837769-0e59-499d-9c1e-b317898d24a3)
![image](https://github.com/user-attachments/assets/ebe25525-93af-4650-a03f-4cada319a988)
![image](https://github.com/user-attachments/assets/a552d607-ad76-4b79-97cb-3c64f9093058)

### Expected behaviour

Recipes should work as intended.

**Comment by Bebobobo** [comment]
this is a known bug with refined storage and gated progression. refined storage dev refuses to fix it so nothing can be done.

**Comment by CharZinta** [comment]
Confirmed. Ticket to be closed.
