### ISSUE TITLE
Trying to host Caveopolis Server, spawns on overworld 

### ISSUE THREAD

**Issue by jjjj12212** [bbl-team/Modpack-Support#28]
### Modpack

Other...

### Version

Caveopolis 5.0 (1.18.2 / 40.2.17)

### Describe the bug

When loading into the server for the first time, Spawned on the overworld (dirt blocks, sky, water).

### Steps to reproduce

1. download Forge 40.2.17 and setup a new server
2. Download Caveopolis5.0_server_pack.zip
3. Unzip at new server directory
4. run start.ps1
5. Connect to server with client using Curseforge. Single Player works, but Multiplayer gets spawned on overworld.

### Expected behaviour

Expecting to spawn underground in a cave just like the single player experience.

**Comment by Azulear** [comment]
Hi, stop your server, remove the world folder and edit the file "server.properties" and set the level-type to
`level-type=skyblockbuilder\:skyblock`
Start your server and check if it is ok.

If this does not work try
`level-type=skyblockbuilder\:custom_skyblock`
It's some time ago, do not remember exacly.

**Comment by Bebobobo** [comment]
you can also check https://discord.com/channels/716249661798612992/987017400480301076

**Comment by jjjj12212** [comment]
@Azulear, Thank you!!! The first one worked like a charm!
