### ISSUE TITLE
industrial fermenter wont build 

### ISSUE THREAD

**Issue by FRANCIS4117** [bbl-team/Modpack-Support#29]
### Modpack

Techopolis 2

### Version

5.4

### Describe the bug

i am useing the engineers hammer on the correct block for the industrial fermenter but it won't build. i have included videos of me looking at the sides to see if it is built incorrectly and then a different one working.

### Steps to reproduce

step 1 build a industrial fermenter
step 2 use the engineers hammer on the middle cauldron
step 3 wonder why it didnt do anything

### Expected behaviour

i expected it to turn in to the industrial fermenter when i used the hammer

### Screenshots

sorry it was too big to send as one file
![fermenter bug part 1 - Made with Clipchamp](https://github.com/user-attachments/assets/2d66f92b-c960-46a6-b49e-104ad23e4b30)
![fermenter bug part 2 - Made with Clipchamp](https://github.com/user-attachments/assets/7f4912e1-c721-46a2-be1c-4f2338e74e28)
i was left and right clicking (it did not change any thing)
and yet this still works
![this works - Made with Clipchamp](https://github.com/user-attachments/assets/ca7ebbaa-780d-4179-9c26-a2e5c460dd23)

**Comment by Bebobobo** [comment]
add 1 block spacing along the edge where there are no blocks.

**Comment by FRANCIS4117** [comment]
there is 
![Screenshot 2024-11-08 141442](https://github.com/user-attachments/assets/7521bf27-06d4-49fb-83ce-d4bf5ba157b6)
or did i miss interpertwhat you meant

**Comment by Bebobobo** [comment]
on the left side

**Comment by FRANCIS4117** [comment]
still not working
![image](https://github.com/user-attachments/assets/562b2657-daca-49ab-8902-1c1687dd6c12)

**Comment by Bebobobo** [comment]
let me load up and check

**Comment by Bebobobo** [comment]
this is the block to right click. 
![image](https://github.com/user-attachments/assets/22b4687d-45f2-43ea-aa81-b1fec028b23e)

**Comment by FRANCIS4117** [comment]
why do i need to do it from that side it just worked from there but that was the block i was clicking from a different side

**Comment by Bebobobo** [comment]
i was unable to form it from any other side than this. this is based on mod requirement, not the pack.

**Comment by FRANCIS4117** [comment]
while thats annoying it should say that in the manual

**Comment by Bebobobo** [comment]
like i said its a mod issue not a pack issue. this may have been resolved in later versions
