### ISSUE TITLE
Quest Incorrect?

### ISSUE THREAD

**Issue by Teraphina** [bbl-team/Modpack-Support#3]
### Modpack

Stoneopolis

### Version

B3.0

### Describe the bug

The quest for grass blocks stated it is made in the blood altar, but "crafting" recipie shows the Alchemy Table?

### Steps to reproduce

open Quest book and look at the seed quest.
open crafting recipie for grass block

### Expected behaviour

per quest desciption should be able to make grass block in blood altar.

**Comment by CharZinta** [comment]
Confirmed. Blood altar is in the description but JEI shows Alchemy or manual crafting option.

**Comment by b0bst3r** [comment]
Misunderstanding of the quest text, lemme break it down:-

![image](https://github.com/bbl-team/Modpack-Support/assets/2760085/acfe28c2-b969-4d76-86cb-05275152e485)
 
Made inside the blood altar <- reference to making the seeds
Turns Dirt Blocks into Grass Blocks when used in the world <- using the seeds on a dirt block turns the dirt block into a grass block.

**Comment by Teraphina** [comment]
Ok that explains it. though you see where the confusion is.

**Comment by Azulear** [comment]
I don't know why it's confusing.
The quest is for creating a grass seed which can turn, in addition, a dirt block into a grass block if you use it on it.
JEI is showing a way to create a grass block.
2 different things in my opinion, so no bug.

**Comment by benbenlaw** [comment]
yeah i think this is fine
