### ISSUE TITLE
Strainers causing Multiplayer server crash

### ISSUE THREAD

**Issue by Cryptic-Stank** [bbl-team/Modpack-Support#5]
### Modpack

Stoneopolis

### Version

B3

### Describe the bug

![Screenshot 2024-04-13 084826](https://github.com/bbl-team/Modpack-Support/assets/166927137/13e6897c-28d8-43f6-bb86-fad6792782da)

Placing a strainer in multiplayer causes a crash, which breaks the server completely since the strainer is placed it there a workaround i can do ? please let me know

### Steps to reproduce

1. craft strainer 2. place strainers 3. crash
![Screenshot 2024-04-13 084826](https://github.com/bbl-team/Modpack-Support/assets/166927137/bc959e8e-2a3d-42cc-90b8-2880153a9727)

### Expected behaviour

To be able to correctly use the strainers

### Screenshots

![Screenshot 2024-04-13 084826](https://github.com/bbl-team/Modpack-Support/assets/166927137/fcfc1951-8abe-4ec5-8d3b-2c1bf6e83c01)

### Additional information

[crash-2024-04-13_08.40.50-client.txt](https://github.com/bbl-team/Modpack-Support/files/14967554/crash-2024-04-13_08.40.50-client.txt)

**Comment by CharZinta** [comment]
This is a ticking block entity error.

Can you confirm these are the coordinates you placed the strainer at
Level spawn location: World: (**0,64,0**), Section: (at 0,0,0 in 0,4,0; chunk contains blocks 0,-64,0 to 15,319,15), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,-64,0 to 511,319,511)

**Comment by benbenlaw** [comment]
so taking a look now and it seems to be with the way the rendering is running, this also effects the drying table
