### ISSUE TITLE
Crash on SMP login / Need a server update for the modpack

### ISSUE THREAD

**Issue by bigor44** [bbl-team/Modpack-Support#7]
### Modpack

Techopolis 2

### Version

2.7.0

### Describe the bug

Hi,
I am unable to connect to my server. No error on server log
Clientside: 
I obtain an unclear error and i am not able to determine what's the issue

Crashreport
[crash-2024-04-24_14.10.38-client.txt](https://github.com/bbl-team/Modpack-Support/files/15093922/crash-2024-04-24_14.10.38-client.txt)

### Steps to reproduce

I use the serverpack available on curseforge website and the modpack with the curseforge client.
With no config change, the smp login indicates multiple mods missing serverside alongside mods version mismatches.
I uploaded manualy the missings or updated mods and dependancies on my server and modify the forge version to 43.3.2

### Expected behaviour

login to distant server

### Screenshots

![image](https://github.com/bbl-team/Modpack-Support/assets/37290775/7cccb649-6633-4bf5-a123-225f1cf11557)

**Comment by b0bst3r** [comment]
The server download on the main page (bottom right corner) is an old version (look at the dates on the pack).  To find the latest server download do this 
![image](https://github.com/bbl-team/Modpack-Support/assets/2760085/e4ae6f83-4bf5-4cdb-a495-910503800cdb)

Wipe the server - reinstall the new version - do not overwrite under any circumstances as you will mix everything up.

**Comment by bigor44** [comment]
Thanks a lot :)
