### ISSUE TITLE
Everything is unfamiliar after game crash

### ISSUE THREAD

**Issue by hagmanine** [bbl-team/Modpack-Support#9]
### Modpack

Stoneopolis

### Version

2.1

### Describe the bug

My game crashed and now all items are unfamiliar, even the stone pebbles.

### Steps to reproduce

I crafted the void and placed it down. As soon as i entered it, the game crashed.

### Expected behaviour

Entering the voide

### Screenshots

![image](https://github.com/bbl-team/Modpack-Support/assets/170371500/4c1effa4-de93-426a-9aae-250ec5de85a0)
![image](https://github.com/bbl-team/Modpack-Support/assets/170371500/1df1e3c1-24b2-43de-894f-6660575d0cda)
![image](https://github.com/bbl-team/Modpack-Support/assets/170371500/4123eef0-2b76-4d24-9004-b59037949af1)

### Additional information

 Is there a way to reload so that all the stages are back without starting from the beginning?

**Comment by CharZinta** [comment]
Please go into stoneopolis 1, and welcome to stoneopolis and hover over any item to confirm there is no dependencies that got reset. The "unfamiliar item" means you didn't complete a quest. While I understand that you did the system thinks you did not. So we check for the red triangle, top left corner, first then there are commands to run that might help.
